baseurl: ""
url: "

https://codecrux.com"

twitter_username: codecrux
github_username:  codecrux

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

gems:
  - jekyll-seo-tag

collections:
  cookies:
    output: true
