
baseurl: ""
url: "http://codecrux.com"

twitter_username: codecrux
github_username:  codecrux

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag

collections:
  cookies:
    output: true
