
title: CodeCrux - Smart, Data-Driven and Outcome focussed Product Development Company
email: contact@codecrux.com
contact_email: shyam@codecrux.com

description: Smart, Data-Driven and Outcome focussed Products
baseurl: ""
url: "http://codecrux.com"

twitter_username: codecrux
github_username:  codecrux

# Build settings
markdown: kramdown
